### PR TITLE
Fail build if packaging step fails

### LINKED ISSUE #114: Package script fails should fail build
If generating the nuget package in AppVeyor fails, the entire build should fail.

### PR DESCRIPTION
**Pull request by mhoeger**
Resolves #114

PowerShell doesn't automatically fail if an .exe the PowerShell script calls fails ([some context](https://stackoverflow.com/questions/9948517/how-to-stop-a-powershell-script-on-the-first-error)). 

Solution is to error if any errors were found.

### CODE REVIEW

**Comment by mhoeger** [comment]
@pragnagopa :)

**Comment by mhoeger** [comment]
@pragnagopa - mind taking a look again? did some more searching and found a cleaner solution, since we don't really care how long it takes us to fail.

**Comment by pragnagopa** [comment]
Looks cleaner! Can you give an example when does the script failure take longer?

**Comment by mhoeger** [comment]
This guy: https://ci.appveyor.com/project/appsvc/azure-functions-nodejs-worker/build/1.0.10075-pvcsbmps

Before, we were failing as soon as the script encountered an error, now we're waiting until the end. But it isn't too bad since the artifacts don't publish and it doesn't take tooo long :)

**Comment by mhoeger** [comment]
@pragnagopa - the `exit $errors.Count` solution only works locally, as there appear to be many issues on appveyor that are actually benign (on a build we think is green, the error count is 256).

**Pull request merged**
