### PR TITLE
fix rawbody => rawBody

### PR DESCRIPTION
**Pull request by mhoeger**

### CODE REVIEW

**Comment by altano** [comment]
@mhoeger thanks for fixing this. This bit me today. +1 if you can get it merged and released to npm :)

**Comment by mhoeger** [comment]
@altano - the change should be in npm! You may need to delete your package-lock.json and try again. Note that the prerelease version is what was incremented, which may be why you're not seeing it right away!

**Comment by altano** [comment]
@mhoeger yeah I'm using the released, stable version not the pre-release. I'll wait for it to make its way to the stable version. Thanks!

**Comment by altano** [comment]
Oh, I misunderstood, `latest` points at `1.0.2-beta2`. I updated and now have the fix. Thanks!

**Pull request merged**
