### PR TITLE
fix: rebuild types

### PR DESCRIPTION
**Pull request by G-Rath**
@mhoeger sorry, I realised I didn't run `npm run build` for #359 😞

### CODE REVIEW

**Review by mhoeger — APPROVED** [review]
That's my bad too - thanks for catching :)

**Comment by G-Rath** [comment]
If you like, I could setup a basic github action to check if PRs need to run this :)

**Comment by mhoeger** [comment]
Love it! Yeah, I would be very grateful :) We generally use Azure DevOps over GitHub Actions across our repos, so a change to [this yaml](https://github.com/Azure/azure-functions-nodejs-worker/blob/v2.x/azure-pipelines.yml) is more consistent with what we've done, but anything you add I would add to the DevOps pipeline anyways. Thanks!!

**Comment by G-Rath** [comment]
@mhoeger interesting - based off that config, you should already have hecks running on PRs that'd catch this; so I'm guessing the issue is actually the CI isn't configured properly to come through on GitHub?

**Pull request merged**
