### PR TITLE
Handle multiple workers

### PR DESCRIPTION
**Pull request by ejizba**

### CODE REVIEW

**Review by hossam-nasr — COMMENTED** [review]
This makes sense, but don't we need to update the default version of `@azure/functions` shipped in Azure to be one where a valid `functionId` is being sent to the worker before we can merge this with the host?

**Comment by ejizba** [comment]
This only applies to v4 of the library, which is not the default

**Review by hossam-nasr — APPROVED** [review]

**Comment by hossam-nasr** [comment]
Created an issue here: https://github.com/Azure/azure-functions-nodejs-library/issues/28 to track this for v4 to make sure we don't forget and also approved :)

**Comment by ejizba** [comment]
Closing in favor of https://github.com/Azure/azure-functions-nodejs-worker/pull/641

**Pull request closed without merging**
